version: "3.8"

services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - 8100:80
    depends_on:
      - app
    environment:
      HOST: app
      PORT: 8080

  app:
    build:
      context: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./app/:/app
    ports:
      - 2345:2345
    stdin_open: true
    tty: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
      - redis
      - createbuckets

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo

  redis:
    image: redis:6.2.3
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/redis/data/redis:/data

  minio:
    image: minio/minio:RELEASE.2021-05-27T22-06-31Z
    ports:
      - 9000:9000
    command: server /export
    environment:
      - MINIO_ACCESS_KEY=golang
      - MINIO_SECRET_KEY=password
    volumes:
      - minio-data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=golang
      - MINIO_SECRET_KEY=password
      - HOST=local
      - BUCKET1=default-bucket
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add $${HOST} http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb $${HOST}/$${BUCKET1};
      /usr/bin/mc policy download $${HOST}/$${BUCKET1};
      exit 0;
      "
volumes:
  minio-data: